// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSbI2b1PcuTcQPPIgInAtNfeeLSsh6riA',
    appId: '1:66296289375:web:10accb665305f90c7ae3ea',
    messagingSenderId: '66296289375',
    projectId: 'pemrogramaniot-5ee42',
    authDomain: 'pemrogramaniot-5ee42.firebaseapp.com',
    storageBucket: 'pemrogramaniot-5ee42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8_aknOdwO9NxCMZJmClPSKvgJ2q2kq5w',
    appId: '1:66296289375:android:e9ee743937c6fd2d7ae3ea',
    messagingSenderId: '66296289375',
    projectId: 'pemrogramaniot-5ee42',
    storageBucket: 'pemrogramaniot-5ee42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbCAwVR_ahFQfidwRPazfX445u2D5sy8s',
    appId: '1:66296289375:ios:6425514f25b8fa237ae3ea',
    messagingSenderId: '66296289375',
    projectId: 'pemrogramaniot-5ee42',
    storageBucket: 'pemrogramaniot-5ee42.appspot.com',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbCAwVR_ahFQfidwRPazfX445u2D5sy8s',
    appId: '1:66296289375:ios:e69dd76038549a4d7ae3ea',
    messagingSenderId: '66296289375',
    projectId: 'pemrogramaniot-5ee42',
    storageBucket: 'pemrogramaniot-5ee42.appspot.com',
    iosBundleId: 'com.example.iot.RunnerTests',
  );
}
